//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    public partial class CUSTOMER
    {
        public string CUSTID { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string PHONENUMBER { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string CREDITCARDTYPE { get; set; }
        public string CREDITCARDNUMBER { get; set; }
        public string STATUS { get; set; }
    }
}
