//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace DataAccess
{
    public partial class ORDERS
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERS()
        {
            this.ITEMS = new HashSet<ITEMS>();
        }
    
        public Nullable<decimal> CUSTID { get; set; }
        public decimal ORDID { get; set; }
        public Nullable<DateTime> ORDERDATE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string STATUS { get; set; }
        public string COMMENTS { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMS> ITEMS { get; set; }
    }
}
