-- USER SQL
ALTER USER "CLIENT_DB"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS

-- ROLES
ALTER USER "CLIENT_DB" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES