package aes.pica.touresbalon.touresbalonproductosws.entidades.productos;
// Generated Oct 16, 2016 11:26:44 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Campanias generated by hbm2java
 */
public class Campanias  implements java.io.Serializable {


     private int idCampania;
     private int idProducto;
     private Date fechaInicio;
     private Date fechaFin;

    public Campanias() {
    }

    public Campanias(int idCampania, int idProducto, Date fechaInicio, Date fechaFin) {
       this.idCampania = idCampania;
       this.idProducto = idProducto;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public int getIdCampania() {
        return this.idCampania;
    }
    
    public void setIdCampania(int idCampania) {
        this.idCampania = idCampania;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


