package aes.pica.touresbalon.reservas.entidades.dann;
// Generated 19-oct-2016 1:21:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PublicReservations generated by hbm2java
 */
public class PublicReservations  implements java.io.Serializable {


     private int idPublicReservation;
     private Room room;
     private Date checkInDate;
     private Date checkOutDate;
     private Set touresbalonReservationses = new HashSet(0);

    public PublicReservations() {
    }

	
    public PublicReservations(int idPublicReservation, Room room) {
        this.idPublicReservation = idPublicReservation;
        this.room = room;
    }
    public PublicReservations(int idPublicReservation, Room room, Date checkInDate, Date checkOutDate, Set touresbalonReservationses) {
       this.idPublicReservation = idPublicReservation;
       this.room = room;
       this.checkInDate = checkInDate;
       this.checkOutDate = checkOutDate;
       this.touresbalonReservationses = touresbalonReservationses;
    }
   
    public int getIdPublicReservation() {
        return this.idPublicReservation;
    }
    
    public void setIdPublicReservation(int idPublicReservation) {
        this.idPublicReservation = idPublicReservation;
    }
    public Room getRoom() {
        return this.room;
    }
    
    public void setRoom(Room room) {
        this.room = room;
    }
    public Date getCheckInDate() {
        return this.checkInDate;
    }
    
    public void setCheckInDate(Date checkInDate) {
        this.checkInDate = checkInDate;
    }
    public Date getCheckOutDate() {
        return this.checkOutDate;
    }
    
    public void setCheckOutDate(Date checkOutDate) {
        this.checkOutDate = checkOutDate;
    }
    public Set getTouresbalonReservationses() {
        return this.touresbalonReservationses;
    }
    
    public void setTouresbalonReservationses(Set touresbalonReservationses) {
        this.touresbalonReservationses = touresbalonReservationses;
    }




}


