package aes.pica.touresbalon.reservas.entidades.dann;
// Generated 19-oct-2016 1:21:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Room generated by hbm2java
 */
public class Room  implements java.io.Serializable {


     private int roomNumber;
     private Hotel hotel;
     private String type;
     private String price;
     private Set publicReservationses = new HashSet(0);

    public Room() {
    }

	
    public Room(int roomNumber, Hotel hotel) {
        this.roomNumber = roomNumber;
        this.hotel = hotel;
    }
    public Room(int roomNumber, Hotel hotel, String type, String price, Set publicReservationses) {
       this.roomNumber = roomNumber;
       this.hotel = hotel;
       this.type = type;
       this.price = price;
       this.publicReservationses = publicReservationses;
    }
   
    public int getRoomNumber() {
        return this.roomNumber;
    }
    
    public void setRoomNumber(int roomNumber) {
        this.roomNumber = roomNumber;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public Set getPublicReservationses() {
        return this.publicReservationses;
    }
    
    public void setPublicReservationses(Set publicReservationses) {
        this.publicReservationses = publicReservationses;
    }




}


