package aes.pica.touresbalon.reservas.entidades.dann;
// Generated 19-oct-2016 1:21:42 by Hibernate Tools 4.3.1



/**
 * TouresbalonReservations generated by hbm2java
 */
public class TouresbalonReservations  implements java.io.Serializable {


     private int reserId;
     private PublicReservations publicReservations;
     private int state;
     private String guestName;

    public TouresbalonReservations() {
    }

	
    public TouresbalonReservations(int reserId, PublicReservations publicReservations) {
        this.reserId = reserId;
        this.publicReservations = publicReservations;
    }
    public TouresbalonReservations(int reserId, PublicReservations publicReservations, int state, String guestName) {
       this.reserId = reserId;
       this.publicReservations = publicReservations;
       this.state = state;
       this.guestName = guestName;
    }
   
    public int getReserId() {
        return this.reserId;
    }
    
    public void setReserId(int reserId) {
        this.reserId = reserId;
    }
    public PublicReservations getPublicReservations() {
        return this.publicReservations;
    }
    
    public void setPublicReservations(PublicReservations publicReservations) {
        this.publicReservations = publicReservations;
    }
    public int getState() {
        return this.state;
    }
    
    public void setState(int state) {
        this.state = state;
    }
    public String getGuestName() {
        return this.guestName;
    }
    
    public void setGuestName(String guestName) {
        this.guestName = guestName;
    }




}


