CREATE TABLE [dbo].[CIUDAD] (
    [ID_CIUDAD]   NVARCHAR (50)  NOT NULL,
    [PAIS]        NVARCHAR (MAX) NULL,
    [TIPO_CIUDAD] NUMERIC (18)   NULL,
    PRIMARY KEY CLUSTERED ([ID_CIUDAD] ASC),
    CONSTRAINT [FK_CIUDAD_TIPO_CIUDAD] FOREIGN KEY ([TIPO_CIUDAD]) REFERENCES [dbo].[TARIFA_CIUDAD] ([ID])
);

