package aes.pica.touresbalon.touresbalonproductosws.entidades.clientesyordenes;
// Generated 24/09/2016 07:35:07 PM by Hibernate Tools 4.3.1



/**
 * CustomerAddressId generated by hbm2java
 */
public class CustomerAddressId  implements java.io.Serializable {


     private Integer custid;
     private Integer addrid;

    public CustomerAddressId() {
    }

    public CustomerAddressId(Integer custid, Integer addrid) {
       this.custid = custid;
       this.addrid = addrid;
    }
   
    public Integer getCustid() {
        return this.custid;
    }
    
    public void setCustid(Integer custid) {
        this.custid = custid;
    }
    public Integer getAddrid() {
        return this.addrid;
    }
    
    public void setAddrid(Integer addrid) {
        this.addrid = addrid;
    }




}


