package aes.pica.touresbalon.touresbalonproductosws.entidades.clientesyordenes;
// Generated 3/10/2016 09:51:13 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CustomerAddressId generated by hbm2java
 */
public class CustomerAddressId  implements java.io.Serializable {


     private int custid;
     private int addrid;

    public CustomerAddressId() {
    }

    public CustomerAddressId(int custid, int addrid) {
       this.custid = custid;
       this.addrid = addrid;
    }
   
    public int getCustid() {
        return this.custid;
    }
    
    public void setCustid(int custid) {
        this.custid = custid;
    }
    public int getAddrid() {
        return this.addrid;
    }
    
    public void setAddrid(int addrid) {
        this.addrid = addrid;
    }

}


