CREATE
  TABLE dann.HOTEL
  (
    HOTEL_ID         INTEGER NOT NULL ,
    NAME             VARCHAR2 (4000 CHAR) ,
    ADDRESS          VARCHAR2 (4000 CHAR) ,
    CITY             VARCHAR2 (4000 CHAR) ,
    COUNTRY          VARCHAR2 (4000 CHAR) 
  ) ;
ALTER TABLE dann.HOTEL ADD CONSTRAINT HOTEL_PK PRIMARY KEY ( HOTEL_ID )
;


CREATE
  TABLE dann.PUBLIC_RESERVATIONS
  (
    ID_PUBLIC_RESERVATION INTEGER NOT NULL ,
    CHECK_IN_DATE         DATE ,
    CHECK_OUT_DATE        DATE ,
    ROOM_NUMBER           INTEGER NOT NULL
  ) ;
ALTER TABLE dann.PUBLIC_RESERVATIONS ADD CONSTRAINT
PUBLIC_RESERVATIONS_PK PRIMARY KEY ( ID_PUBLIC_RESERVATION ) ;


CREATE
  TABLE dann.ROOM
  (
    ROOM_NUMBER INTEGER NOT NULL ,
    TYPE        VARCHAR2 (4000 CHAR) ,
    PRICE       VARCHAR2 (4000 CHAR),
    HOTEL_ID INTEGER NOT NULL
  ) ;
ALTER TABLE dann.ROOM ADD CONSTRAINT ROOM_PK PRIMARY KEY ( ROOM_NUMBER )
;


CREATE
  TABLE dann.TOURESBALON_RESERVATIONS
  (
    RESER_ID               INTEGER NOT NULL ,
    STATE                  INTEGER ,
    GUEST_NAME             VARCHAR2 (4000 CHAR) ,
    PUBLIC_RESERVATIONS_ID INTEGER NOT NULL
  ) ;
ALTER TABLE dann.TOURESBALON_RESERVATIONS ADD CONSTRAINT
TOURESBALON_RESERVATIONS_PK PRIMARY KEY ( RESER_ID ) ;

ALTER TABLE dann.ROOM ADD CONSTRAINT HOTEL_ID_FK FOREIGN KEY (
HOTEL_ID ) REFERENCES dann.HOTEL ( HOTEL_ID ) ;

ALTER TABLE dann.TOURESBALON_RESERVATIONS ADD CONSTRAINT
PUBLIC_RESERVATIONS_FK FOREIGN KEY ( PUBLIC_RESERVATIONS_ID ) REFERENCES
dann.PUBLIC_RESERVATIONS ( ID_PUBLIC_RESERVATION ) ;

ALTER TABLE dann.PUBLIC_RESERVATIONS ADD CONSTRAINT
PUBLIC_RESERVATIONS_ROOM_FK FOREIGN KEY ( ROOM_NUMBER ) REFERENCES
dann.ROOM ( ROOM_NUMBER ) ;


CREATE SEQUENCE dann.HOTEL_ID_SEC START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE dann.ROOM_NUMER_SEC START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE dann.PUBLIC_RESERVATION_SEC START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE dann.RES_TB_SEC START WITH 1 NOCACHE ORDER ;


COMMIT;