INSERT INTO HOTEL (HOTEL_ID,NAME,CITY,COUNTRY,ADDRESS) VALUES (HOTEL_ID_SEC.NEXTVAL,'DANN CARLTON','BOGOTA','COLOMBIA','CALLE FALSA 123'); 
INSERT INTO ROOM (ROOM_NUMBER,TYPE,PRICE,HOTEL_ID) VALUES (ROOM_NUMER_SEC.NEXTVAL,'SINGLE','500000',1);
INSERT INTO ROOM (ROOM_NUMBER,TYPE,PRICE,HOTEL_ID) VALUES (ROOM_NUMER_SEC.NEXTVAL,'DOUBLE','600000',1);
INSERT INTO ROOM (ROOM_NUMBER,TYPE,PRICE,HOTEL_ID) VALUES (ROOM_NUMER_SEC.NEXTVAL,'IMPERIAL','1600000',1);

INSERT INTO PUBLIC_RESERVATIONS (ID_PUBLIC_RESERVATION,ROOM_NUMBER) VALUES (PUBLIC_RESERVATION_SEC.NEXTVAL,1);
INSERT INTO PUBLIC_RESERVATIONS (ID_PUBLIC_RESERVATION,ROOM_NUMBER) VALUES (PUBLIC_RESERVATION_SEC.NEXTVAL,2);
INSERT INTO PUBLIC_RESERVATIONS (ID_PUBLIC_RESERVATION,ROOM_NUMBER) VALUES (PUBLIC_RESERVATION_SEC.NEXTVAL,3);


INSERT INTO TOURESBALON_RESERVATIONS 
(RESER_ID,GUEST_NAME,STATE,PUBLIC_RESERVATIONS_ID) 
VALUES (RES_TB_SEC.NEXTVAL,'JUAN',1,1);