//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_TouresBalon.ServicioProductos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/ServicioProductos")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private B2C_TouresBalon.ServicioProductos.Ciudad ciudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string espectaculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_llegadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_salidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private B2C_TouresBalon.ServicioProductos.TarifaTipo tipo_espectaculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private B2C_TouresBalon.ServicioProductos.TarifaTipo tipo_hospedateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private B2C_TouresBalon.ServicioProductos.TarifaTipo tipo_transporteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public B2C_TouresBalon.ServicioProductos.Ciudad ciudad {
            get {
                return this.ciudadField;
            }
            set {
                if ((object.ReferenceEquals(this.ciudadField, value) != true)) {
                    this.ciudadField = value;
                    this.RaisePropertyChanged("ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string espectaculo {
            get {
                return this.espectaculoField;
            }
            set {
                if ((object.ReferenceEquals(this.espectaculoField, value) != true)) {
                    this.espectaculoField = value;
                    this.RaisePropertyChanged("espectaculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_llegada {
            get {
                return this.fecha_llegadaField;
            }
            set {
                if ((this.fecha_llegadaField.Equals(value) != true)) {
                    this.fecha_llegadaField = value;
                    this.RaisePropertyChanged("fecha_llegada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_salida {
            get {
                return this.fecha_salidaField;
            }
            set {
                if ((this.fecha_salidaField.Equals(value) != true)) {
                    this.fecha_salidaField = value;
                    this.RaisePropertyChanged("fecha_salida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_producto {
            get {
                return this.id_productoField;
            }
            set {
                if ((this.id_productoField.Equals(value) != true)) {
                    this.id_productoField = value;
                    this.RaisePropertyChanged("id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public B2C_TouresBalon.ServicioProductos.TarifaTipo tipo_espectaculo {
            get {
                return this.tipo_espectaculoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_espectaculoField, value) != true)) {
                    this.tipo_espectaculoField = value;
                    this.RaisePropertyChanged("tipo_espectaculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public B2C_TouresBalon.ServicioProductos.TarifaTipo tipo_hospedate {
            get {
                return this.tipo_hospedateField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_hospedateField, value) != true)) {
                    this.tipo_hospedateField = value;
                    this.RaisePropertyChanged("tipo_hospedate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public B2C_TouresBalon.ServicioProductos.TarifaTipo tipo_transporte {
            get {
                return this.tipo_transporteField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_transporteField, value) != true)) {
                    this.tipo_transporteField = value;
                    this.RaisePropertyChanged("tipo_transporte");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ciudad", Namespace="http://schemas.datacontract.org/2004/07/ServicioProductos")]
    [System.SerializableAttribute()]
    public partial class Ciudad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_ciudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private B2C_TouresBalon.ServicioProductos.TarifaTipo tipo_ciudadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_ciudad {
            get {
                return this.id_ciudadField;
            }
            set {
                if ((this.id_ciudadField.Equals(value) != true)) {
                    this.id_ciudadField = value;
                    this.RaisePropertyChanged("id_ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                if ((object.ReferenceEquals(this.paisField, value) != true)) {
                    this.paisField = value;
                    this.RaisePropertyChanged("pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public B2C_TouresBalon.ServicioProductos.TarifaTipo tipo_ciudad {
            get {
                return this.tipo_ciudadField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_ciudadField, value) != true)) {
                    this.tipo_ciudadField = value;
                    this.RaisePropertyChanged("tipo_ciudad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TarifaTipo", Namespace="http://schemas.datacontract.org/2004/07/ServicioProductos")]
    [System.SerializableAttribute()]
    public partial class TarifaTipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre_tipo {
            get {
                return this.nombre_tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_tipoField, value) != true)) {
                    this.nombre_tipoField = value;
                    this.RaisePropertyChanged("nombre_tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioProductos.IServicioProductos")]
    public interface IServicioProductos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/DoWork", ReplyAction="http://tempuri.org/IServicioProductos/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/DoWork", ReplyAction="http://tempuri.org/IServicioProductos/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/ConsultarProductos", ReplyAction="http://tempuri.org/IServicioProductos/ConsultarProductosResponse")]
        B2C_TouresBalon.ServicioProductos.Producto[] ConsultarProductos(string palabraClave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/ConsultarProductos", ReplyAction="http://tempuri.org/IServicioProductos/ConsultarProductosResponse")]
        System.Threading.Tasks.Task<B2C_TouresBalon.ServicioProductos.Producto[]> ConsultarProductosAsync(string palabraClave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/ConsultarPromociones", ReplyAction="http://tempuri.org/IServicioProductos/ConsultarPromocionesResponse")]
        B2C_TouresBalon.ServicioProductos.Producto[] ConsultarPromociones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/ConsultarPromociones", ReplyAction="http://tempuri.org/IServicioProductos/ConsultarPromocionesResponse")]
        System.Threading.Tasks.Task<B2C_TouresBalon.ServicioProductos.Producto[]> ConsultarPromocionesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioProductosChannel : B2C_TouresBalon.ServicioProductos.IServicioProductos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioProductosClient : System.ServiceModel.ClientBase<B2C_TouresBalon.ServicioProductos.IServicioProductos>, B2C_TouresBalon.ServicioProductos.IServicioProductos {
        
        public ServicioProductosClient() {
        }
        
        public ServicioProductosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioProductosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProductosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProductosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public B2C_TouresBalon.ServicioProductos.Producto[] ConsultarProductos(string palabraClave) {
            return base.Channel.ConsultarProductos(palabraClave);
        }
        
        public System.Threading.Tasks.Task<B2C_TouresBalon.ServicioProductos.Producto[]> ConsultarProductosAsync(string palabraClave) {
            return base.Channel.ConsultarProductosAsync(palabraClave);
        }
        
        public B2C_TouresBalon.ServicioProductos.Producto[] ConsultarPromociones() {
            return base.Channel.ConsultarPromociones();
        }
        
        public System.Threading.Tasks.Task<B2C_TouresBalon.ServicioProductos.Producto[]> ConsultarPromocionesAsync() {
            return base.Channel.ConsultarPromocionesAsync();
        }
    }
}
