package aes.pica.touresbalon.touresbalonproductosws.entidades.clientesyordenes;
// Generated 21-sep-2016 23:28:23 by Hibernate Tools 4.3.1



/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private String addrid;
     private String street;
     private String state;
     private String zip;
     private String country;
     private String addresstype;
     private String city;

    public Address() {
    }

	
    public Address(String addrid) {
        this.addrid = addrid;
    }
    public Address(String addrid, String street, String state, String zip, String country, String addresstype, String city) {
       this.addrid = addrid;
       this.street = street;
       this.state = state;
       this.zip = zip;
       this.country = country;
       this.addresstype = addresstype;
       this.city = city;
    }
   
    public String getAddrid() {
        return this.addrid;
    }
    
    public void setAddrid(String addrid) {
        this.addrid = addrid;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getAddresstype() {
        return this.addresstype;
    }
    
    public void setAddresstype(String addresstype) {
        this.addresstype = addresstype;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }




}


