package aes.pica.touresbalon.reservas.entidades.clientesyordenes;
// Generated 18-oct-2016 11:57:06 by Hibernate Tools 4.3.1



/**
 * CustomerAddressId generated by hbm2java
 */
public class CustomerAddressId  implements java.io.Serializable {


     private int custid;
     private int addrid;

    public CustomerAddressId() {
    }

    public CustomerAddressId(int custid, int addrid) {
       this.custid = custid;
       this.addrid = addrid;
    }
   
    public int getCustid() {
        return this.custid;
    }
    
    public void setCustid(int custid) {
        this.custid = custid;
    }
    public int getAddrid() {
        return this.addrid;
    }
    
    public void setAddrid(int addrid) {
        this.addrid = addrid;
    }  

}