DROP TABLE ADDRESS CASCADE CONSTRAINTS
;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS
;
DROP TABLE CUSTOMER_ADDRESS CASCADE CONSTRAINTS
;
DROP TABLE ITEMS CASCADE CONSTRAINTS
;
DROP TABLE ORDERS CASCADE CONSTRAINTS
;

CREATE TABLE ADDRESS
(
	STREET       VARCHAR2(40),
	STATE        VARCHAR2(40),
	ZIP          VARCHAR2(10),
	COUNTRY      VARCHAR2(40),
	ADDRESSTYPE  VARCHAR2(10),
	ADDRID       VARCHAR2(4000) NOT NULL,
	CITY         VARCHAR2(40)
)
;


CREATE TABLE CUSTOMER
(
	CUSTID            VARCHAR2(40) NOT NULL,
	FNAME             VARCHAR2(40),
	LNAME             VARCHAR2(40),
	PHONENUMBER       VARCHAR2(40),
	EMAIL             VARCHAR2(40),
	PASSWORD          VARCHAR2(40),
	CREDITCARDTYPE    VARCHAR2(40),
	CREDITCARDNUMBER  VARCHAR2(40),
	STATUS            VARCHAR2(10)
)
;


CREATE TABLE CUSTOMER_ADDRESS
(
	CUSTID     VARCHAR2(20) NOT NULL,
	ADDRESSID  VARCHAR(4000) NOT NULL
)
;


CREATE TABLE ITEMS
(
	ITEMID       VARCHAR2(10) NOT NULL,
	PRODID       NUMBER(22),
	PRODUCTNAME  VARCHAR2(50),
	PARTNUM      VARCHAR2(20),
	PRICE        NUMBER(9,2),
	QUANTITY     NUMBER(9),
	ORDID        VARCHAR2(10) NOT NULL
)
;


CREATE TABLE ORDERS
(
	CUSTID     VARCHAR2(10),
	ORDID      VARCHAR2(10) NOT NULL,
	ORDERDATE  DATE,
	PRICE      NUMBER(9,2),
	STATUS     VARCHAR2(10),
	COMMENTS   VARCHAR2(4000)
)
;



CREATE INDEX IXFK_CUSTOMER_ADDRESS_CUSTOMER ON CUSTOMER_ADDRESS
(CUSTID ASC)
;

ALTER TABLE ADDRESS ADD CONSTRAINT PK_ADDRESS 
	PRIMARY KEY (ADDRID)
;

ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER 
	PRIMARY KEY (CUSTID)
;

ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT PK_CUSTOMER_ADDRESS 
	PRIMARY KEY (ADDRESSID)
;

ALTER TABLE ITEMS ADD CONSTRAINT PK_ITEMS 
	PRIMARY KEY (ITEMID)
;

ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDERS 
	PRIMARY KEY (ORDID)
;



ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT FK_CUSTOMER_ADDRESS_CUSTOMER 
	FOREIGN KEY (CUSTID) REFERENCES CUSTOMER (CUSTID)
;

ALTER TABLE ITEMS ADD CONSTRAINT FK_ITEMS_ORDERS 
	FOREIGN KEY (ORDID) REFERENCES ORDERS (ORDID)
;

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_CUSTOMER 
	FOREIGN KEY (CUSTID) REFERENCES CUSTOMER (CUSTID)
;
