IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CIUDAD') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CIUDAD
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('PRODUCTO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE PRODUCTO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TARIFA_CIUDAD') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TARIFA_CIUDAD
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TARIFA_ESPECTACULO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TARIFA_ESPECTACULO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TARIFA_HOSPEDAJE') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TARIFA_HOSPEDAJE
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TARIFA_TRANSPORTE') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TARIFA_TRANSPORTE
;


CREATE TABLE CIUDAD ( 
	ID_CIUDAD varchar(4000) NOT NULL,
	PAS varchar(4000),
	TIPO_CIUDAD numeric(18)
)
;

CREATE TABLE PRODUCTO ( 
	ID numeric(18) NOT NULL,
	ESPECTACULO varchar(4000) NOT NULL,
	FECHA_ESPECTACULO date,
	CIUDAD_ESPECTACULO varchar(4000),
	FECHA_LLEGADA varchar(4000),
	FECHA_SALIDA varchar(4000),
	TIPO_TRANSPORTE numeric(18),
	TIPO_ESPECTACULO numeric(18),
	TIPO_HOSPEDAJE numeric(18)
)
;

CREATE TABLE TARIFA_CIUDAD ( 
	ID numeric(18) NOT NULL,
	NOMBRE_TIPO varchar(4000),
	PRECIO float
)
;

CREATE TABLE TARIFA_ESPECTACULO ( 
	ID numeric(18) NOT NULL,
	NOMBRE_TIPO varchar(4000),
	PRECIO float
)
;

CREATE TABLE TARIFA_HOSPEDAJE ( 
	ID numeric(18) NOT NULL,
	NOMBRE_TIPO varchar(4000),
	PRECIO float
)
;

CREATE TABLE TARIFA_TRANSPORTE ( 
	ID numeric(18) NOT NULL,
	NOMBRE_TIPO varchar(4000),
	PRECIO float
)
;


ALTER TABLE CIUDAD ADD CONSTRAINT CIUDAD_PK 
	PRIMARY KEY CLUSTERED (ID_CIUDAD)
;

ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_PK 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE TARIFA_CIUDAD ADD CONSTRAINT TARIFA_CIUDAD_PK 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE TARIFA_ESPECTACULO ADD CONSTRAINT TARIFA_ESPECTACULO_PK 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE TARIFA_HOSPEDAJE ADD CONSTRAINT PK_TARIFA_HOSPEDAJE 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE TARIFA_TRANSPORTE ADD CONSTRAINT TARIFA_TRANSPORTE_PK 
	PRIMARY KEY CLUSTERED (ID)
;
