IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CAMPANIA_PRODUCTO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CAMPANIA DROP CONSTRAINT FK_CAMPANIA_PRODUCTO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PRODUCTO_CIUDAD') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PRODUCTO DROP CONSTRAINT FK_PRODUCTO_CIUDAD
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PRODUCTO_TARIFA_HOSPEDAJE') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PRODUCTO DROP CONSTRAINT FK_PRODUCTO_TARIFA_HOSPEDAJE
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PRODUCTO_TARIFA_ESPECTACULO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PRODUCTO DROP CONSTRAINT FK_PRODUCTO_TARIFA_ESPECTACULO
;



IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CAMPANIA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CAMPANIA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CIUDAD') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CIUDAD
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('PRODUCTO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE PRODUCTO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TARIFA_CIUDAD') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TARIFA_CIUDAD
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TARIFA_ESPECTACULO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TARIFA_ESPECTACULO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TARIFA_HOSPEDAJE') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TARIFA_HOSPEDAJE
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TARIFA_TRANSPORTE') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TARIFA_TRANSPORTE
;


CREATE TABLE CAMPANIA ( 
	ID_CAMPANIA numeric(18) NOT NULL,
	NOMBRE_CAMPANIA varchar(50),
	DESCRIPCION varchar(200),
	ID_PRODUCTO numeric(18),
	FECHA_INICIAL datetime,
	FECHA_FINAL datetime
)
;

CREATE TABLE CIUDAD ( 
	ID_CIUDAD numeric(18) NOT NULL,
	NOMBRE_CIUDAD varchar(4000),
	PAIS varchar(4000),
	ID_TARIFA_CIUDAD numeric(18)
)
;

CREATE TABLE PRODUCTO ( 
	ID_PRODUCTO numeric(18) NOT NULL,
	NOMBRE_PRODUCTO varchar(4000),
	ID_ESPECTACULO numeric(18),
	ID_TRANSPORTE numeric(18),
	ID_HOSPEDAJE numeric(18),
	ID_CIUDAD numeric(18),
	FECHA_SALIDA datetime,
	FECHA_LLEGADA datetime,
	FECHA_ESPECTACULO datetime,
	URL_IMAGEN varchar(1000)
)
;

CREATE TABLE TARIFA_CIUDAD ( 
	ID_TARIFA_CIUDAD numeric(18) NOT NULL,
	TIPO_CIUDAD varchar(50),
	PRECIO float
)
;

CREATE TABLE TARIFA_ESPECTACULO ( 
	ID_ESPECTACULO numeric(18) NOT NULL,
	NOMBRE_ESPECTACULO varchar(4000),
	PRECIO float
)
;

CREATE TABLE TARIFA_HOSPEDAJE ( 
	ID_HOSPEDAJE numeric(18) NOT NULL,
	NOMBRE_HOSPEDAJE varchar(4000),
	PRECIO float
)
;

CREATE TABLE TARIFA_TRANSPORTE ( 
	ID_TRANSPORTE numeric(18) NOT NULL,
	NOMBRE_TRANSPORTE varchar(4000),
	PRECIO float
)
;


ALTER TABLE CAMPANIA ADD CONSTRAINT PK_CAMPANIA 
	PRIMARY KEY CLUSTERED (ID_CAMPANIA)
;

ALTER TABLE CIUDAD ADD CONSTRAINT CIUDAD_PK 
	PRIMARY KEY CLUSTERED (ID_CIUDAD)
;

ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_PK 
	PRIMARY KEY CLUSTERED (ID_PRODUCTO)
;

ALTER TABLE TARIFA_CIUDAD ADD CONSTRAINT TARIFA_CIUDAD_PK 
	PRIMARY KEY CLUSTERED (ID_TARIFA_CIUDAD)
;

ALTER TABLE TARIFA_ESPECTACULO ADD CONSTRAINT TARIFA_ESPECTACULO_PK 
	PRIMARY KEY CLUSTERED (ID_ESPECTACULO)
;

ALTER TABLE TARIFA_HOSPEDAJE ADD CONSTRAINT PK_TARIFA_HOSPEDAJE 
	PRIMARY KEY CLUSTERED (ID_HOSPEDAJE)
;

ALTER TABLE TARIFA_TRANSPORTE ADD CONSTRAINT TARIFA_TRANSPORTE_PK 
	PRIMARY KEY CLUSTERED (ID_TRANSPORTE)
;



ALTER TABLE CAMPANIA ADD CONSTRAINT FK_CAMPANIA_PRODUCTO 
	FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
;

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO_CIUDAD 
	FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD (ID_CIUDAD)
;

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO_TARIFA_HOSPEDAJE 
	FOREIGN KEY (ID_HOSPEDAJE) REFERENCES TARIFA_HOSPEDAJE (ID_HOSPEDAJE)
;

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO_TARIFA_ESPECTACULO 
	FOREIGN KEY (ID_ESPECTACULO) REFERENCES TARIFA_ESPECTACULO (ID_ESPECTACULO)
;
