package aes.pica.touresbalon.touresbalonproductosws.entidades.clientesyordenes;
// Generated 21-sep-2016 23:28:23 by Hibernate Tools 4.3.1



/**
 * CustomerAddress generated by hbm2java
 */
public class CustomerAddress  implements java.io.Serializable {


     private String addressid;
     private Customer customer;

    public CustomerAddress() {
    }

    public CustomerAddress(String addressid, Customer customer) {
       this.addressid = addressid;
       this.customer = customer;
    }
   
    public String getAddressid() {
        return this.addressid;
    }
    
    public void setAddressid(String addressid) {
        this.addressid = addressid;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }




}


