package aes.pica.touresbalon.touresbalonproductosws.entidades.clientesyordenes;
// Generated 3/10/2016 10:30:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Items generated by hbm2java
 */
public class Items  implements java.io.Serializable {


     private int itemid;
     private Orders orders;
     private int prodid;
     private String productname;
     private String partnum;
     private double price;
     private int quantity;

    public Items() {
    }

	
    public Items(int itemid, Orders orders) {
        this.itemid = itemid;
        this.orders = orders;
    }
    public Items(int itemid, Orders orders, int prodid, String productname, String partnum, double price, int quantity) {
       this.itemid = itemid;
       this.orders = orders;
       this.prodid = prodid;
       this.productname = productname;
       this.partnum = partnum;
       this.price = price;
       this.quantity = quantity;
    }
   
    public int getItemid() {
        return this.itemid;
    }
    
    public void setItemid(int itemid) {
        this.itemid = itemid;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public int getProdid() {
        return this.prodid;
    }
    
    public void setProdid(int prodid) {
        this.prodid = prodid;
    }
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }
    public String getPartnum() {
        return this.partnum;
    }
    
    public void setPartnum(String partnum) {
        this.partnum = partnum;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


